# Pre-commit hooks para Versos de Protesta
repos:
  - repo: local
    hooks:
      # Hook principal: actualizar diccionario antes del commit
      - id: update-dictionary
        name: 🔄 Update Dictionary
        entry: bash -c 'npm run update-content && git add src/data/'
        language: system
        files: '^src/content/blog/d[ií]a-.*\.md$'
        pass_filenames: false
        verbose: true
        
      # Hook de validación simple con bash
      - id: validate-lesson-frontmatter
        name: 📋 Validate Lesson Frontmatter
        entry: scripts/check-frontmatter.sh
        language: system
        files: '^src/content/blog/d[ií]a-.*\.md$'
        pass_filenames: true

  # Hooks estándar de calidad (solo esenciales)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$'
      - id: end-of-file-fixer
        exclude: '\.json$'
      - id: check-json
        files: '^src/data/.*\.json$'
      - id: check-added-large-files
        args: ['--maxkb=1000']